name: build

on:
  push:
    branches:
      - main
      - 'patch-to-v*'
  pull_request:
    branches:
      - main
      - 'patch-to-v*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      publish_docker: false
      platforms: 'linux/amd64'
    secrets:
      CICD_GITHUB_PAT: ${{ secrets.CICD_GITHUB_PAT }}
